# Generated by Django 3.2.5 on 2021-07-16 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.FloatField()),
                ('release_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('genres', models.CharField(blank=True, default='', max_length=300)),
                ('playtime', models.DurationField()),
                ('imdb_url', models.URLField(blank=True)),
                ('jw_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielist', models.ManyToManyField(blank=True, help_text='The movies belonging to this movielist.', related_name='profile', related_query_name='profile', to='api.Movie', verbose_name='movies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
